### ISSUE TITLE
💛💛💛 check this and say yes

### ISSUE THREAD

**Issue by yizhenzha** [Nahemah1022/SingSphere#2]
Luv u so much that I wanna spend the rest of my life with you💛💛 Would you say yes babe?

**Comment by Nahemah1022** [comment]
Yes!!

**Comment by Nahemah1022** [comment]
@madiliu Thanks for bringing us together!

**Comment by LuminaScript** [comment]
> @madiliu Thanks for bringing us together!

如此想要見證人嗎哈哈哈哈

**Comment by madiliu** [comment]
見證人已被閃瞎…..😎😎😎
